# -*- coding: utf-8 -*-
"""solved_bootcamp_assignment_005_Oct_16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B2DvNpQuvEqZnnHKf2jnrTswL5WKWYG4

# ASSIGNMENTS 
## Send it before 0000 hrs IST or 12 AM Friday

## NOTE: Evaluation will be done before next class.

## HOW TO SUBMIT: -
Download this notebook, Solve it and upload in the google form given in the mail.

# List, Tuple and Sets

#### 1. On amazon website we have the following available items - 

```python
amazon_website = [("watch", 5000), ("phone", 10000), ("laptop", 50000), ("shirt", 1000)]
```
Take the user input N no. of times and find out the total cost to be paid?

OR

You can ask the user quntity or the count of item?

if the item is not present in the amazon website then print that item as out of stock and do add it total


HINT: while, for loop.. indexing
"""

amazon_website = [("watch", 5000), ("phone", 10000), ("laptop", 50000), ("shirt", 1000)]
o = [i[-1] for i in amazon_website]
user_input = int(input('Enter no. of times :'))
print('Total cost to be paid ? ', sum(o) * user_input)

"""#### 2. What will be the output of the following code snippet?

```
arr = [1, 2, 3, 4, 5, 6]
for i in range(1, 6):
    arr[i - 1] = arr[i]
for i in range(0, 6): 
    print(arr[i], end = " ")
```

OUtput: 2 3 4 5 6 6

#### 3. Write a Python program to find the repeated items of a tuple.
"""

t = (2, 4, 5, 6, 2, 3, 4, 4, 7)
rep = {x for x in t if t.count(x) > 1}
print('Repeated items in tuplex: ', rep)

"""### 4. Replace last value of tuples in a list with 500. Try using list comprehension

Example -: 
```
Input -:

[(10, 20, 40), (40, 50, 60), (70, 80, 90)]

Output -:
[(10, 20, 500), (40, 50, 500), (70, 80, 500)]


```

"""

my_list = [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
input = [lists[:-1] + tuple([500]) for lists in my_list]
print(input)