# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFyVHRsbUf20lxviriylQzgXeAvOhW6I

ASSIGNMENTS NUMBER : 2
"""

numbers = [12, 75, 150, 180, 145, 525, 50]
def max_num(numbers):
  larjest_number = numbers[0]
  for num in numbers:
    if num > larjest_number:
      larjest_number = num
      continue 
  return larjest_number
print('Greater Number Is :', max_num(numbers))

for x in range(1, 12):
  if x % 2 == 0:
    print('EVEN NUMBER IS :', x)

n = int(input('Enter a Number :'))
sum = 0
for i in range(1, n):
  sum += i
print('Sum of Number is :', sum + (i +1))

num = [12, 75, 150, 180, 145, 525, 50]
count = []
for div in num:
  if div % 5 == 0 and div != 150:
    if div > 500:
      break
    count.append(div)
print('Number is Divisible by 5:', count)

list11 = [10, 20, 30, 40, 50]
print('Reverse Order of list :', list1[::-1])