# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VK8qvFxeMpV-upbWhQS5lmxxKcGHisF3

Answer 1. Diffrent Types of error encountered in Today Lecture I have present in below whith causes..   Variable Case senstivity
"""

REC = 333
print(rec)

del rec

"""Reserved words in Python"""

print = 'aba'
print('abc')

del print

"""Multi assignment of variables"""

a,A, b,c, C = 3,4,3,4,5
print(f"""Number a is :{a}, Number A is :{A}  , Number b is: {b} , Number c is {c}, Number C is :{C}""")





"""Default str by through user input?
   it's  by default Why : need to help 
  

**we can convert float to int not int to float 
same as we can string to int can't int to str
same int to bool not bool to int **
"""

A = input("Enter value of A: ")
print(type(A))
print(f"Value is in String data type: {A}")

b= 5 
print(type(b))
# my question is : why user data type not contain by default same data type if use put the value of int type
# but in this case it's taking by default data type as well as

"""Answer 2.  input A and B and print their sum, mul, div, square """

A = float(input("Enter value of A: "))
B = float(input("Enter value of B: "))

print(f"Sum of A and B is: {A+B}")
print(f"Multi of A and B is: {A*B}")
print(f"Sqa of A and B is: {A**B}")
print(f"Div of A and B is: {A/B}")



"""Answer 3.
33 Reserved keywords in python 3.7 
because all reserve keyw expext True And Flase value


AnD Ans4., ans 5 in below
"""

firstName = input("Enter your firstName: ")
lastName = input("Enter your lastName: ")
domain = '@gmail.com'
print (f"Your Email id is : {lastName}.{firstName}{domain}")

name = input(" Your Name: ")
place = input("Your address: ")
money = input("How much you earn daily : ")

print(f"""
My name is: {name}
My address is: {place}
i earn daily: {money} $
""")



"""Ans 6 AND ANS 7"""

firstName = input("Enter your firstName: ")
lastName = input("Enter your lastName: ")
domain = '@gmail.com'
current_year = input("current year: ")
year_of_birth = input("current year: ")
age = int(current_year) - int(year_of_birth)

print(f"""
Your First name is: {name}
you live at: {place}
your age is in year
: {age}
""")
print(f"Your Email id is : {lastName}.{firstName}{domain}")

A = 22.4
A = int(A)
print(f"data type after: {type(A)}, value of A: {A}")

A = 22
A = complex(A)
print(f"data type after: {type(A)}, value of A: {A}")