# -*- coding: utf-8 -*-
"""Assignment_002

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uBM0dSuBhf6Wc87qHmVqQJ5OdYjA6Elb

Answer 1. Diffrent Types of error encountered when indentation wil not be coreect: indentation is a way of telling the interpreter that a series of statements belong to a particular block of code. Variable Case senstivity. all the statements with the same distance (space) to the right, belong to the same block etc..

Answer 2:
"""

class_started = bool(input("Hey friend, is class started?: [0-False, 1-True]"))
if class_started:
    print("Since class started...")
    print("Lets concentrate")
else:
    print("Since class is not started...")
    print("let's revise")

"""Answer 3:"""

#  Use if else condition to verify that dataype of `input()` method in python is always string.

input_value = input('Enter a Value :')
if type(input_value) == str:
  print('by default user input value will be string')
else:
  print('by default user input value will be another data type')

""" Ans 4: Take 3 variables and assign integer values to them. Find the largest variable, by only using the if and else conditions."""

a = 2  
b = 4
c = 8
if a > b:
  if a >c:
    print('a is greter than b & c')
  else:
    print('c is greater than a & b')
else:
  if b > c:
    print('b is greater than a & c')
  else:
    print('c is greater than a & b')

"""Ans 5: False because no of no = yes

"""

a = 6
b = 10
print( not ( not a == 10 or not b == 10) )

"""Ans 6: a is b means located same addre(id)   && a = b means same value of diff addre(id)"""

A = 5.0
B = 10/2
C = A
print(A is B)
print(A is C)
# - case 2:
A = 5.0
B = int(10/2)
print(A is B)
# - case 3:
A = 5.0
B = float(10/2)
print(A is B)

"""Ans 7:
Write a program that asks the user to enter a number. You should print out a message to the user, either “That number is divisible by either 3 or 5”, or “That number is not divisible by either 3 or 5”. Be sure to consider the data type of the input you are taking in from the user. Use a single if/else block to solve this problem.
"""

num = float(input('Enter a Number :'))
if num % (3 and 5) == 0:
  print('Number is divisible by 3 and 5')
else:
  print('Number is not divisible by 3 and 5')

"""Ans 8:Take user input for length and width. Then calculate the area of rectangle. Also print as per length and width whether its a square of rectangle."""

length = float(input('Enter length of rectangle :'))
width = float(input('Enter width of rectangle :'))
area_rec = length * width
print('Area of rectangle :',
      area_rec)

"""Ans 9:
Take two variable radius_1 and radius_2 and calculate the area of circle_1 and circle_2. Also print which circle has large area. If area is equal then print area is equal.
"""

radius_1 = float(input('Enter a radius of circle 1 :'))
radius_2 = float(input('Enter redius of circle 2'))
area_c1 = radius_1 * radius_1
area_c2 = radius_2 * radius_2
if area_c1 > area_c2:
  print('area of radius_1 is large tha radius_2')
elif area_c1 < area_c2:
  print('area of radius_1 is less than radius_2') 
else:
  print('Area of circle is equal radius_1 and 2')

"""Ans 10:

Check whether a year is leap year or not. Use nested if...else to solve this problem. A leap year is exactly divisible by 4 except for century years (years ending with 00). The century year is a leap year only if it is perfectly divisible by 400.
"""

year = int(input('Enter a Year'))
# year divided by 4 is a leap year
if (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
# year is not leap year
else:
    print("{0} is not a leap year".format(year))