# -*- coding: utf-8 -*-
"""ans_assignment_003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFisIyzm_jab7r15JmC2nwo-uvgfJHdb

Ans 1:
Count the number of times iNeuron appears in the string.
"""

text = "Welcome to iNeuron, You are a part of FSDS Bootcamp 2 in iNeuron. I hope you are enjoying the course by iNeuron"
print('The number of times iNeuron appearing :', text.count('iNeuron'))

"""Ans 2:
Check if position 5 to 11 ends with the phrase iNeuron. in the string

"""

txt = "Hello, welcome to FSDS 2.0 at iNeuron."
if txt[5:11] == 'iNeuron':
  print('Yes it is iNeuron')
else:
  print('not in txt iNeuron')

"""Ans 3:
Write a program that takes your full name as input and displays the abbreviations of the first and middle names except the last name which is displayed as it is. For example, if your name is Sunny Bhaveen Chandra, then the output should be S.B.Chandra.


"""

f_name = input('Enter Your name :')
m_name  = input('Enter your Middle Name :')
l_name = input('Enter your Last Name :')
print(f'your name is : {f_name} {m_name} {l_name}')
print(f'Your Shot Name is :{f_name[0]}.{m_name[0]}.{l_name}')

"""Ans 4:
Join all items in a list into a string, using a hash(#) character as separator:
"""

LIST = ["My", "name", "is", "Rishav", "Dash"]
'#'.join(LIST)

"""Ans 5:
Write example for the following string manipulation function,

- isdecimal()
- islower()
- isupper()
- isalpha()
- isnumeric()
"""

# Lower
name = "Vivek Kumar Tiwari"
print(f'In Lower Name: {name.lower()}')
# Upper
name = "Vivek Kumar Tiwari"
print(f'In Upper Name:{name.upper()}')
name = "Vivek Kumar Tiwari"
print(f'In Decimal Name :{name.isdecimal()}')
name = "Vivek Kumar Tiwari"
print(f'In Alpha Name :{name.isalpha()}')
name = "Vivek Kumar Tiwari"
print(f'In Numeric Name:{name.isnumeric()}')

"""Ans 6:
Indian PAN card format follows the following formats -

    AYEPC7894X
    ABCDE9999Y Take user input for PAN_CARD and validate as per the above example.


"""



pan = (input('Enter Pan Number :')).upper()
if len(pan) == 10:
  if pan[0:5].isalpha():
    if pan[5:8].isdigit():
      if pan[9:].isalpha():
        print(f'Your {pan} Number Is valid')
else:
  print('Your Pan Number is not Valid \n please Try Again in Formate ABCDE9999Y ')