# -*- coding: utf-8 -*-
"""demo_003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enM8CCFDUy2Tp3W4q24DLilHOtVe7i_e

Common ques
1. can we use lab? YES
2. Can we use Jupyter notebook locally? YES
3. Can we use neuro lab? YES
4. Can we use VSCODE? YES
4. Can we use PyCharm? YES
5. Can we use Colab? YES
6. Can we code simultaneosly code? YES definitely

# AGENDA
1. Variable Case senstivity [clear]
2. Reserved words in Python [clear]
3. Multi assignment of variables [clear]
4. User input [clear]
5. type casting | type conversion [Doubt at the end]
6. Memory block []
7. Operators
  - Logical
  - Equality
  - Comparision
  - Arthimatic
  - Bitwise [Advance classes]
  - Operators for sets and dictionary [Advance classes]

8. String methods

## Variable Case senstivity

variable names defined as

Ashish ashish
"""

TEN = 10
ten = 20
# TEN and ten both are different in terms of lowercase and uppercase letter

print(Ten)

TEN

"""## Reserved words in Python

https://docs.python.org/2.5/ref/keywords.html

1. We should not use reserved words as variable names
2. Also python doesn't restrict the user to use reserved keywords as variable names
"""

print("Hi there")

print = "Hi there" # as a variable
type(print)

print("Hi there")

print = 12 # as a variable
type(print)

print("Hi there")

del print # delete the variable print

print("Hi there")

Print = "Hi there" # as a variable
type(Print)

print("Hi there")

print = 10

type(print)

del print

print("Sunny")

"""## Multi assignment of variables"""

a, b, c, yes = 10, 20.2, "Sunny", True

type(a)

type(b)

type(c)

type(yes)

type(a)

print(type(a))
print(type(b))
print(type(c))
print(type(yes))

# a,b,c = 10

a,b,c = 10,10,10

a, A, c, C = 10, 20.2, "Sunny", True

print(a, A, c, C)

a=b=c=10

a,b,c

firstName, middleName, sirName = "Sunny", "Bhaveen", "Chandra"

print(f"{firstName}.{sirName}@gmail.com")

name, place, year_of_birth, weight = "Sunny", "Bengaluru", 1991, 80.88

print(f"""
My name is: {name}
I live at: {place}
I was born in: {year_of_birth}
My weight is: {weight} in Kgs
""")

"""# NOTE: Before can i use? Please try in colab or jupyter notebook once

## User input
"""

name = input("Enter your Name: ")

print(f"You have entered: {name}")

A = input("Enter value of A: ")
B = input("Enter value of B: ")

print(f"Sum of A and B is: {A+B}")

print("Sum of A and B is: {A+B}")

A = input("Enter value of A: ")
B = input("Enter value of B: ")

print(type(A), type(B))

name = input("Name: ")
place = input("place: ")
year_of_birth = input("year_of_birth: ")

print(f"""
My name is: {name}
I live at: {place}
I was born in: {year_of_birth}
""")

# calcualte the age of the user

name = input("Name: ") # always gives you string values
place = input("place: ")
year_of_birth = input("year_of_birth: ")

age = 2022 - year_of_birth

print(f"""
My name is: {name}
I live at: {place}
{name} is of age: {age}
""")

# calcualte the age of the user

name = input("Name: ") # always gives you string values
place = input("place: ")
year_of_birth = int(input("year_of_birth: ")) # convert this into integer

age = 2022 - year_of_birth

print(f"""
My name is: {name}
I live at: {place}
{name} is of age: {age}
""")

# calcualte the age of the user

name = input("Name: ") # always gives you string values
place = input("place: ")
year_of_birth = input("year_of_birth: ") # convert this into integer

age = 2022 - int(year_of_birth)

print(f"""
My name is: {name}
I live at: {place}
{name} is of age: {age}
""")

# calcualte the age of the user

name = input("Name: ") # always gives you string values
place = input("place: ")
year_of_birth = input("year_of_birth: ") # convert this into integer
current_year = input("current year: ")
age = int(current_year) - int(year_of_birth)

print(f"""
My name is: {name}
I live at: {place}
{name} is of age: {age}
""")

"""## Type conversion

We can convert the data type of one variable into another if it is allowed

"""

A = int(input("Enter value of A: "))
B = int(input("Enter value of B: "))

print(type(A), type(B))

print(f"Sum of A and B is: {A+B}")

int A

A = float(input("Enter value of A: "))
B = float(input("Enter value of B: "))

print(f"Sum of A and B is: {A+B}")

A = float(input("Enter value of A: "))
B = int(input("Enter value of B: "))

print(f"Sum of A and B is: {A+B}")

A = float(input("Enter value of A: "))
B = int(input("Enter value of B: ")) # 10.2 is float but converting to int

print(f"Sum of A and B is: {A+B}")

# String to integer
A = "50"
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A)
print(f"data type after: {type(A)}, value of A: {A}")

# String to integer
A = "50.22" # entering float
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A) # trying to convert into integer
print(f"data type after: {type(A)}, value of A: {A}")

# float to integer
A = 50.22
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A)
print(f"data type after: {type(A)}, value of A: {A}")

# integer to float
A = 50
print(f"data type before: {type(A)}, value of A: {A}")
A = float(A)
print(f"data type after: {type(A)}, value of A: {A}")

# integer to boolean
A = 10
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

"""* True in binary - 1 
* False in binary - 0 
"""

# integer to boolean
A = 0
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# integer to boolean
A = 1
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

"""> NOTE: Converting any non zero number and string values into boolean will give True as an answer

> NOTE: Empty string "" will give False as an answer after converting from string to boolean
"""

# integer to boolean
A = -5
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# string to boolean
A = "Sunny"
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# string to boolean
A = "True"
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# string to boolean
A = "False"
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# empty string to boolean
A = ""
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# empty string to boolean
A = " "
print(f"data type before: {type(A)}, value of A: {A}")
A = bool(A)
print(f"data type after: {type(A)}, value of A: {A}")

# empty string to int
A = ""
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A)
print(f"data type after: {type(A)}, value of A: {A}")

"""## Memory block """

a = 22
b = 34
c = 22

id(a) # memory address

id(b)

id(c)

c = 22 + b

id(c)

a = 22
id(a)

a = 99
id(a)

"""Memory is assigned to the value of variable passed not the variable name"""

a = 22
b = 34
c = 22 

print(id(a), id(b), id(c))

a = "Sunny"
b = 34
c = "Sunny"

print(id(a), id(b), id(c))

a = "S"
b = 34
c = "S"

print(id(a), id(b), id(c))

a = 22
b = 34
c = 22.0 

print(id(a), id(b), id(c))

"""# LIVE DOUBTS"""

name = input("Name: ")
YOB = int(input("YOB: ")) # string

age = 2022 - YOB
print(age)

"""# ASSIGNMENTS - NOT compulsory but usefull!!
# I am not at loss if you don't submit
## send the mail to 
## send it before 0000 hrs IST | 12 AM tonight
## Special cases respond atleast before 1200 hrs IST tomorrow i.e Monday

TO: query@ineuron.ai
CC: sunny@ineuron.ai, riishav@ineuron.ai, boktiar@ineuron.ai
 
Subject: [Bootcamp 2.0 | Assignment No. 1]: 

1. Find out all the types of error that we have encountered in our lecture and why? Also include the examples.
2. Take input A and B and print their sum, mul, div, square of the nos.
3. How many reserve keywords are there in python and why we should not use them as a variable name.
4. Create email ids with the user inputs. in the following format - 
lastname.firstname@gmail.com
5. Try to print the following lines - 
  - Hi I'm Sunny
  - My address is 22\3 
  - I earn 20$ daily.
6. Take user input (name, address, date of birth etc) to fill a form for your college and print their email IDs
7. Convert the following - 
  - "22.4" into integer
  - "22" into complex no.

"""

x = input("Enter the value of x: ")

x =  22.2
bool(x)

x =  22
bool(x)

x =  0.0
bool(x)

x =  0
bool(x)

x =  -22
bool(x)

x =  -22.2
bool(x)

i_have_a_doubt = input("yes? ")
bool(i_have_a_doubt)

i_have_a_doubt = input("yes? ")
bool(i_have_a_doubt)

25.88 + 10

round(25.88 + 10, 2)

25.89 + 10

def sum_of_values(x, y):
  print(x+y)

sum_of_values(22.2, 33, 444)

