# -*- coding: utf-8 -*-
"""FSDS_bootcamp_assignment_002_Oct_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aa0M0VLr8RtHx1ZBjghnHzAm18gXX2XB

# ASSIGNMENTS - Compulsory
## Send it before 0000 hrs IST or 12 AM Wednesday

## NOTE: Evaluation will be done before next class.

## HOW TO SUBMIT: -
Download this notebook, Solve it and upload in the google form given in the mail.

1. What is indentation error? Why indentation is important? Give one simple example?

2. Correct the following code and write the comment where you made the correction?

  ```python
  class_started = bool(input("Hey friend, is class started?: [0-False/1-True]"))

  if class_started:
      print("Since class started...")
      print("Lets concentrate")
  else:
      print("Since class is not started...")
      print("let's revise")    
  ```

  **HINT:** Refer your data type conversion class

3. Use if else condition to verify that dataype of `input()` method in python is always string.

4. Take 3 variables and assign integer values to them. Find the largest variable, by only using the if and else conditions.


5. What would be the solution?
    1. True
    2. False

    ```python
    a = 6
    b = 10
    print( not ( not a == 10 or not b == 10) )
    ```
    
6. Find the answer as well as find out the reason behind the result? -
    - case 1:
        ```python
        A = 5.0
        B = 10/2
        print(A is B)
        ```
    - case 2:
        ```python
        A = 5.0
        B = int(10/2)
        print(A is B)
        ```
    - case 3:
        ```python
        A = 5.0
        B = float(10/2)
        print(A is B)
        ```

### Try to understand the following examples and answer the question based on it - 
    
**Arithmatic Operators**

|Operation|Meaning|
|:-:|:-:|
| **+** |addition|
| **-** |subtraction|
| **\*** |multiplication|
| **/** |true division|
| **//** |integer division|
| **%** |the modulo operator|


Here `+`, `-`, `*`, `/` are regular arithmatic operators. Lets look at the `//` and `%` operators

Usecase or examples - 
    
```python
var_a = 5
var_b = 25
integer_division = var_b // var_a
print(f"integer division: {var_b}/{var_a}={integer_division}")
```

OUTPUT: integer division: 25/5=5

```python
var_a = 3
var_b = 25
integer_division = var_b // var_a
print(f"integer division: {var_b}/{var_a}={integer_division}")
```

OUTPUT: integer division: 25/3=8

```python
var_a = 5
var_b = 25
remainder = var_b % var_a
print(f"remainder: {var_b}/{var_a} is {remainder}")
```

OUTPUT: remainder: 25/5 is 0

```python
var_a = 3
var_b = 25
remainder = var_b % var_a
print(f"remainder: {var_b}/{var_a} is {remainder}")
```

OUTPUT: remainder: 25/3 is 1

### Answer below questions on the above theory - 

7. Write a program that asks the user to enter a number. You should print out a message to the user, either “That number is divisible by either 3 or 5”, or “That number is not divisible by either 3 or 5”. Be sure to consider the data type of the input you are taking in from the user. Use a single if/else block to solve this problem.

8. Take user input for length and width. Then calculate the area of rectangle. Also print as per length and width whether its a square of rectangle.

9. Take two variable radius_1 and radius_2 and calculate the area of circle_1 and circle_2. Also print which circle has large area. If area is equal then print area is equal.

10. Check whether a year is leap year or not. Use nested if...else to solve this problem. A leap year is exactly divisible by 4 except for century years (years ending with 00). The century year is a leap year only if it is perfectly divisible by 400.
"""

