# -*- coding: utf-8 -*-
"""FSDS_bootcamp_assignment_004_Oct_09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmME82uJIv6XbDx3XMCHOutw6U1ZLI7E

# ASSIGNMENTS 
## Send it before 0000 hrs IST or 12 AM Wednesday

## NOTE: Evaluation will be done before next class.

## HOW TO SUBMIT: -
Download this notebook, Solve it and upload in the google form given in the mail.

## control flow and conditional statements

Q1. Find the largest number from the given list, use for loop.

```
numbers = [12, 75, 150, 180, 145, 525, 50]
```

Q2. Print all the even number between (1, 12).

Q3. Calculate the sum of all numbers from 1 to a given number
    
    Expected Output:

    Enter number 10
    
    Sum is:  55

Q4. Write a program to display only those numbers from a list that satisfy the following conditions

- The number must be divisible by five

- If the number is greater than 150, then skip it and move to the next number

- If the number is greater than 500, then stop the loop
"""

# Given:

numbers = [12, 75, 150, 180, 145, 525, 50]

"""Q5. Print the given list in reverse order.

```
list1 = [10, 20, 30, 40, 50]
```
"""

